- name: Create zookeeper config file
  template: src=zoo.cfg.j2 dest=/etc/zookeeper/conf/zoo.cfg
  sudo: yes

- name: Create zookeeper myid file
  copy:
    content: "{{zookeeper_id}}"
    dest: /etc/zookeeper/conf/myid
    mode: 0644
  sudo: yes
  notify:
    - Start zookeeper
