---
# tasks file for marathon
- name: remove marathon override
  command: /bin/rm -f /etc/init/marathon.override

- name: ensure marathon is running (and enable it at boot)
  service: name=marathon state=started enabled=yes
