---
# tasks file for haproxy
- name: "assures {{ consul_template_dir }} dirs exists"
  file:
    path: "{{ consul_template_dir }}/{{ item.path }}"
    state: directory
  sudo: yes
  with_items:
    - { path: 'config' }
    - { path: 'templates' }
  tags:
    - haproxy

- name: upload template config files
  template:
    src: "{{ item.src }}"
    dest: "{{ consul_template_dir }}/{{ item.dst }}"
    mode: 0644
  sudo: yes
  with_items:
  - { src: haproxy.tmpl.j2, dst: 'templates/haproxy.tmpl' }
  - { src: consul.cfg.j2, dst: 'config/consul.cfg' }
  tags:
    - haproxy

- name: upload static config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ consul_template_dir }}/{{ item.dst }}"
    mode: 0644
  sudo: yes
  with_items:
    - { src: haproxy.cfg, dst: 'config/haproxy.cfg' }
  tags:
    - haproxy

- name: deploy haproxy service
  become: yes
  become_user: root
  template:
    src: haproxy.service.j2
    dest: /etc/systemd/system/haproxy.service
  notify:
    - reload systemd
    - restart haproxy
  tags:
    - haproxy

- name: ensure haproxy is running (and enable it at boot)
  become: yes
  service:
    name: haproxy
    state: started
    enabled: yes
  tags:
    - haproxy
