---
# tasks file for haproxy
- name: assures {{ consul_template_dir }} dirs exists
  file: path={{ consul_template_dir }}/{{ item.path }} state=directory
  with_items:
    - { path: 'config' }
    - { path: 'templates' }

- name: upload template config files
  template: src=consul.cfg.j2 dest="{{ consul_template_dir }}/config/consul.cfg" mode=0644
  sudo: yes

- name: upload static config files
  copy: src={{ item.src }} dest="{{ consul_template_dir }}/{{ item.dst }}" mode=0644
  sudo: yes
  with_items:
    - { src: haproxy.cfg, dst: 'config/haproxy.cfg' }
    - { src: haproxy.tmpl, dst: 'templates/haproxy.tmpl' }

- name: run haproxy container
  docker:
    name: haproxy
    image: "{{ haproxy_image }}"
    state: started
    net: host
    restart_policy: always
    env:
      HAPROXY_DOMAIN: "{{ haproxy_domain }}"
      CONSUL_CONFIG: "/config"
      CONSUL_LOGLEVEL: "{{ consul_template_loglevel }}"
      CONSUL_CONNECT: "{{ consul_backend }}"
    volumes:
    - "{{ consul_template_dir }}/config:/config"
    - "{{ consul_template_dir }}/templates:/templates"
