---

# Performance tuning for many concurrent requests
# http://pc-freak.net/blog/resolving-nf_conntrack-table-full-dropping-packet-flood-message-in-dmesg-linux-kernel-log/
- name: increase ip_local_port_range for high traffic permanently
  sudo: yes
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - net.ipv4.ip_local_port_range=1024 65000
    - net.netfilter.nf_conntrack_max=500000
    - net.netfilter.nf_conntrack_generic_timeout=120
    - net.netfilter.nf_conntrack_tcp_timeout_established=54000
    # - net.core.somaxconn=50000
    # - net.ipv4.tcp_max_syn_backlog=30000
    # - net.core.netdev_max_backlog=5000
    - fs.file-max=1000000
    - fs.nr_open= 1000000
    # - net.core.rmem_max = 33554432
    # - net.core.wmem_max = 33554432
    - net.ipv4.tcp_rmem = 4096 16384 33554432
    - net.ipv4.tcp_wmem = 4096 16384 33554432
    - net.ipv4.tcp_mem = 786432 1048576 26777216
    # - net.ipv4.tcp_max_tw_buckets = 360000
    # - net.core.netdev_max_backlog = 2500
    # - vm.min_free_kbytes = 65536
    # - vm.swappiness = 0

# sysctl reload
- name: sysctl reload
  sudo: yes
  command: sysctl -p
  tags:
    - haproxy

# nf_conntrack_max hashsize
- name: increase nf_conntrack_max hashsize
  sudo: yes
  command: echo 262144 > /sys/module/nf_conntrack/parameters/hashsize
  tags:
    - haproxy

- name: increase file-max permanently
  sudo: yes
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - root soft nofile 1000000
    - root hard nofile 1000000
    - "* soft nofile 1000000"
    - "* hard nofile 1000000"

# TCP/UDP Tunning for high b bandwith required

