- name: create consul dirs
  sudo: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ consul_data_dir }}"
    - "{{ consul_config_dir }}"

- name: configure consul
  sudo: yes
  template:
    src: consul.json.j2
    dest: /etc/consul.d/consul.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart consul
  tags:
    - consul
