---
- include: config.yml

- name: deploy consul service
  sudo: yes
  sudo_user: root
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: consul.service.j2
      dest: /etc/systemd/system/consul.service
    - src: consul-discovery.service.j2
      dest: /etc/systemd/system/consul-discovery.service
  notify:
    - restart consul systemd
  tags:
    - consul

- name: enable consul
  sudo: yes
  service:
    name: consul
    enabled: yes
    state: started
  notify:
    - restart consul systemd
  tags:
    - consul

#- name: enable consul-discovery
#  sudo: yes
#  service:
#    name: consul-discovery
#    enabled: yes
#    state: started
#  notify:
#    - restart consul systemd
#  tags:
#    - consul
