---
- hosts: all
  roles:
    - dnsmasq
    - consul

- hosts: mesos_masters
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
    - zookeeper
    - marathon

- hosts: mesos_slaves
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
    - docker
    - weave
