---
# handlers file for mesos
- name: start mesos master
  become: yes
  service:
    name: mesos-master
    state: started

- name: start mesos agent
  become: yes
  service:
    name: mesos-agent
    state: started

- name: restart mesos master
  become: yes
  service:
    name: mesos-master
    state: restarted

- name: restart mesos agent
  become: yes
  service:
    name: mesos-agent
    state: restarted
