---

# Install (docker-py) python package as is a docker module dependency.
- pip: name=docker-py

# tasks file for docker registrator
- name: run registrator container
  docker:
    name: registrator
    image: "{{ registrator_image }}"
    state: started
    restart_policy: always
    net: host
    command: "-internal {{ registrator_uri }}"
    hostname: "{{ hostname }}"
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
