- name: download vault binary
  sudo: yes
  get_url:
    url: "{{ vault_url }}"
    dest: /tmp/vault.zip
    mode: 0755

- name: uncompress vault
  unarchive:
    src: /tmp/vault.zip
    dest: /usr/bin
    copy: no

- name: create vault config directory
  file:
    path: "{{ vault_config_folder }}"
    state: directory
    mode: 0755
  sudo: yes
  tags:
    - vault

- name: upload vault template service
  template:
    src: vault.conf.j2
    dest: /etc/init/vault.conf
    mode: 0755
  sudo: yes
  tags:
    - vault

- name: upload vault default template
  template:
    src: default.j2
    dest: /etc/default/vault
    mode: 0755
  sudo: yes
  tags:
    - vault

- name: upload vault config template
  template:
    src: config.hcl.j2
    dest: "{{ vault_config_folder }}/config.hcl"
    mode: 0755
  sudo: yes
  tags:
    - vault

- name: upload vault weave acl policy template
  template:
    src: acl_weave.hcl.j2
    dest: /etc/vault/acl_weave.hcl
    mode: 0755
  sudo: yes
  tags:
    - vault

- name: upload wait for vault leader script
  sudo: yes
  template:
    src: wait-for-vault-leader.sh.j2
    dest: "{{ vault_config_folder }}/wait-for-vault-leader.sh"
    mode: 0755
  tags:
    - vault

- name: Set vault consul service definition
  sudo: yes
  template:
    src: vault-consul.j2
    dest: "{{ vault_consul_dir }}/vault.json"
  notify:
    - restart consul
