- name: login as root
  run_once: true
  when: vault_root_token is defined
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
  command: "vault auth {{ vault_root_token }}"
  sudo: yes
  tags:
    - vault

- name: write acl weave policy
  run_once: true
  when: vault_root_token is defined
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
  sudo: yes
  command: "{{ vault_acl_weave_policy_command }}"
  register: vault_init_output
  tags:
    - vault

