- name: create weave password
  run_once: true
  when: vault_root_token is defined
  environment:
    VAULT_ADDR: "{{ vault_addr }}"
  command: vault write secret/weave/password value={{ vault_weave_password }}
  sudo: yes
  tags:
    - vault

- meta: flush_handlers
