---
# tasks file for weave
- name: configure weave
  sudo: yes
  template: src=interfaces.j2 dest=/etc/network/interfaces.d/weave.cfg owner=root group=root mode=0644
  notify:
    - Up weave interface
  tags:
    - weave

- name: configure weave bridge for docker
  sudo: yes
  lineinfile: "dest=/etc/default/docker state=present regexp=^DOCKER_OPTS= line='DOCKER_OPTS=\"--bridge=weave --fixed-cidr={{ weave_docker_subnet }}\"'"
  notify:
    - Restart docker
  tags:
    - weave

- name: weave launch
  command: /usr/local/bin/weave launch
  sudo: yes
  tags:
    - weave
