- name: create cassandra config directory
  when: frameworks_cassandra_enabled
  run_once: true
  template:
    src: cassandra-config.j2
    dest: /tmp/cassandra-config
    mode: 0755
  sudo: yes
  tags:
    - cassandra

- name: install dcos-cli cassandra package
  when: frameworks_cassandra_enabled
  run_once: true
  docker:
    name: cassandra
    image: "{{ frameworks_dcos_cli_image }}"
    state: started
    command: "package install --options=/config --yes cassandra"
    volumes:
    - "/tmp/cassandra-config:/config"
    env:
      MESOS_MASTER_URL: "{{ frameworks_mesos_master_url }}"
      MARATHON_URL: "{{ frameworks_marathon_url }}"
  tags:
    - cassandra

- name: uninstall dcos-cli cassandra package
  when: ! frameworks_cassandra_enabled
  run_once: true
  docker:
    name: cassandra
    image: "{{ frameworks_dcos_cli_image }}"
    state: started
    command: "package uninstall cassandra"
    env:
      MESOS_MASTER_URL: "{{ frameworks_mesos_master_url }}"
      MARATHON_URL: "{{ frameworks_marathon_url }}"
  tags:
    - cassandra
