---
# defaults file for weave
# TODO: This "until loop" is here as the consul force restart makes vault achieve
# an unconsitent state without leader for some seconds.
weave_command_login_vault: "until curl --max-redirs 1 -L -XPOST  -d'{\"app_id\": \"{{ vault_weave_app_id }}\", \"user_id\": \"{{ hostvars[inventory_hostname][vault_weave_user_id] }}\"}' {{ vault_addr }}/v1/auth/app-id/login | grep client_token ; do sleep 1; done"
weave_bridge: "
    {%- for host in groups[weave_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        10.2.0.{{ loop.index }}/16
      {%- endif -%}
    {%- endfor -%}
"
weave_server_group: weave_servers
weave_docker_subnet: "
    {%- for host in groups[weave_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        10.2.{{ loop.index }}.0/24
      {%- endif -%}
    {%- endfor -%}
"
weave_launch_peers: "
  {%- set weave_peers = [] -%}
  {%- for host in groups[weave_server_group] -%}
    {%- if host != inventory_hostname and host not in weave_peers -%}
      {% do weave_peers.append(hostvars[host]['ansible_eth0']['ipv4']['address']) %}
    {%- endif -%}
  {%- endfor -%}
  {{ weave_peers|join(' ') }}
"
weave_docker_opts: "--bridge=weave --fixed-cidr={{ weave_docker_subnet }} --dns 172.17.42.1 --dns 8.8.8.8 --dns-search service.{{ consul_domain }}"
weave_scope_url: https://github.com/weaveworks/scope/releases/download/latest_release/scope
weave_scope_dest: /usr/local/bin/scope
